const catalogItems = [
    /* Blank entry
    {
        "title": "",
        "format": "",
        "released": "",
        "msrp": "",
        "crurl": "",
        "amzurl": "",
        "diaburl": "",
        "racsurl": "",
    },
    */
    {
        "title": "Magical Girl Lyrical Nanoha A's",
        "format": "bd",
        "released": "2024-07-30",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/magical-girl-lyrical-nanoha-as-complete-collection-blu-ray-875707040426.html",
        "amzurl": "https://www.amazon.com/Magical-Lyrical-Complete-Collection-Blu-ray/dp/B0D2T198J8",
    },
    {
        "title": "Mazinkaiser",
        "format": "bd",
        "released": "2024-07-30",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/mazinkaiser-original-ova-series-blu-ray-875707040198.html",
        "amzurl": "https://www.amazon.com/Mazinkaiser-Original-Blu-ray-Hiroya-Ishimaru/dp/B0D2SXZF3P",
        "racsurl": "http://www.animecornerstore.com/mazinkaiser.html",
    },
    {
        "title": "Urusei Yatsura: OVA Series Collection",
        "format": "bd",
        "released": "2024-07-30",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/urusei-yatsura-ova-series-collection-blu-ray-875707040594.html",
        "amzurl": "https://www.amazon.com/Urusei-Yatsura-Blu-ray-Fumi-Hirano/dp/B0D2SYP64K",
        "racsurl": "http://www.animecornerstore.com/uryabovase.html",
    },
    {
        "title": "Lupin the Third: The Secret Page of Marco Polo",
        "format": "bd",
        "released": "2024-07-30",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/lupin-the-3rd-the-secret-page-of-marco-polo-blu-ray-875707040792.html",
        "amzurl": "https://www.amazon.com/Lupin-3rd-Secret-Marco-Blu-ray/dp/B0D2SWQQWB",
        "diaburl": "",
        "racsurl": "http://www.animecornerstore.com/lu3rdbsepaof.html",
    },
    {
        "title": "Lupin the Third: Princess of the Breeze",
        "format": "bd",
        "released": "2024-07-30",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/lupin-the-3rd-princess-of-the-breeze-blu-ray-875707040624.html",
        "amzurl": "https://www.amazon.com/Lupin-3rd-Princess-Breeze-Blu-ray/dp/B0D2SZ9C77",
        "racsurl": "http://www.animecornerstore.com/lu3rdbprofbr.html",
    },
    {
        "title": "IGPX: The Complete Stage",
        "format": "bd",
        "released": "2024-05-28",
        "msrp": "69.95",
        "crurl": "https://store.crunchyroll.com/products/igpx-immortal-grand-prix-complete-collection-blu-ray-875707039390.html",
        "amzurl": "https://www.amazon.com/Immortal-Grand-Complete-Collection-Blu-ray/dp/B0CW7GN4CY",
        "racsurl": "http://www.animecornerstore.com/igimgrpr1.html",
    },
    {
        "title": "Sex and Fury",
        "format": "bd",
        "released": "2024-05-28",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/sex-and-fury-movie-blu-ray-875707039222.html",
        "amzurl": "https://www.amazon.com/Sex-Fury-Blu-ray-christina-lindberg/dp/B0CW72TQ7Q",
        "diaburl": "https://diabolikdvd.com/product/sex-and-fury-discotek-blu-ray/",
        "racsurl": "http://www.animecornerstore.com/sexandfury.html",
    },
    {
        "title": "Medabots Spirit: The Original Japanese Language Second Series",
        "format": "sdbd",
        "released": "2024-03-26",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/medabots-spirit-second-series-blu-ray-japanese-language-875707039024.html",
        "amzurl": "https://www.amazon.com/Medabots-Spirits-Japanese-Language-Blu-ray/dp/B0CSF3XY1B",
        "racsurl": "https://www.animecornerstore.com/medabots.html",
    },
    {
        "title": "Chie the Brat: 1st TV Series",
        "format": "bd",
        "released": "2024-05-28",
        "msrp": "69.95",
        "crurl": "https://store.crunchyroll.com/products/chie-the-brat-the-original-first-tv-series-blu-ray-875707039628.html",
        "amzurl": "https://www.amazon.com/Chie-Brat-Original-First-Blu-ray/dp/B0CW7K4C92",
        "racsurl": "http://www.animecornerstore.com/chiebrat.html",
    },
    {
        "title": "Giant Gorg (DVD)",
        "format": "dvd",
        "released": "2016-01-26",
        "msrp": "49.95",
        "oop": "yes",
    },
    {
        "title": "Nutcracker Fantasy",
        "format": "bd",
        "released": "2019-11-26",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/nutcracker-fantasy-blu-ray-875707010122.html",
        "amzurl": "https://www.amazon.com/Nutcracker-Fantasy-Blu-ray/dp/B07Y98L3D3",
        "oop": "yes",
    },
    {
        "title": "Hurricane Polymar (live-action movie)",
        "format": "bd",
        "released": "2024-05-28",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/hurricane-polymar-live-action-movie-blu-ray-875707039826.html",
        "amzurl": "https://www.amazon.com/Hurricane-Polymar-Live-Action-Blu-ray/dp/B0CW7VWXL3",
        "diaburl": "https://diabolikdvd.com/product/hurricane-polymar-live-action-movie-discotek-blu-ray/",
        "racsurl": "https://www.animecornerstore.com/hupo.html",
    },
    {
        "title": "Mobile Cop Jiban",
        "format": "sdbd",
        "released": "2024-07-30",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/mobile-cop-jiban-complete-series-blu-ray-875707039994.html",
        "amzurl": "https://www.amazon.com/Mobile-Cop-Jiban-SDBD-Blu-ray/dp/B0D2RWMM4V",
        "racsurl": "https://www.animecornerstore.com/mobilecopjiban.html",
    },
    {
        "title": "Lovely Complex (live-action movie)",
        "format": "bd",
        "released": "2024-03-26",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/lovely-complex-live-action-movie-blu-ray-875707038621.html",
        "amzurl": "https://www.amazon.com/Lovely-Complex-action-movie-Blu-ray/dp/B0CSF5DKRJ",
        "racsurl": "https://www.animecornerstore.com/lovelycomplex1.html",
    },
    {
        "title": "Space Sheriff Shaider",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "69.95",
        "crurl": "https://store.crunchyroll.com/products/space-sheriff-shaider-complete-series-blu-ray-875707004084.html",
        "amzurl": "https://www.amazon.com/Space-Sheriff-Shaider-Complete-Blu-ray/dp/B0DCHNWSQC",
        "racsurl": "https://www.animecornerstore.com/spshsh1.html",
    },
    {
        "title": "Electric Dragon 80000V",
        "format": "bd",
        "released": "2024-11-26",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/electric-dragon-80000v-movie-blu-ray-875707004626.html",
        "amzurl": "https://www.amazon.com/Electric-Dragon-80-000V-Blu-ray/dp/B0DGVR1B69",
        "racsurl": "https://www.animecornerstore.com/eldr80.html",
    },
    {
        "title": "Kamen Rider V3",
        "format": "bd",
        "released": "2024-11-26",
        "msrp": "79.95",
        "crurl": "https://store.crunchyroll.com/products/kamen-rider-v3-complete-tv-series-blu-ray-875707004220.html",
        "amzurl": "https://www.amazon.com/Kamen-Rider-V3-Complete-Blu-ray/dp/B0DGVTP4BX",
        "racsurl": "https://www.animecornerstore.com/kamenriderv3.html",
    },
    {
        "title": "Space Adventure Cobra: The Movie (4K UHD)",
        "format": "4k",
        "released": "2019-11-26",
        "msrp": "34.95",
        "crurl": "https://store.crunchyroll.com/products/space-adventure-cobra-the-movie-4k-ultra-hd-blu-ray-875707010290.html",
        "amzurl": "https://www.amazon.com/Space-Adventure-Cobra-Movie-Ultra/dp/B07Y98NLPB",
        "racsurl": "https://www.animecornerstore.com/spadco.html",
    },
    {
        "title": "Saber Rider and the Star Sheriffs",
        "format": "sdbd",
        "released": "2023-08-29",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/saber-rider-and-the-star-sheriffs-blu-ray-875707034425.html",
        "amzurl": "https://www.amazon.com/Saber-Rider-Sheriffs-Complete-Blu-ray/dp/B0C76H66QZ",
        "racsurl": "https://www.animecornerstore.com/sariandstsh.html",
    },
    {
        "title": "Mon Colle Knights: Complete English Dubbed TV Series",
        "format": "sdbd",
        "released": "2022-05-31",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/mon-colle-knights-english-language-blu-ray-875707025829.html",
        "amzurl": "https://www.amazon.com/Colle-Knights-Complete-English-SDBD/dp/B09VWM23BP",
    },
    {
        "title": "Mon Colle Knights: Original Uncut Japanese Language Edition",
        "format": "sdbd",
        "released": "2021-04-27",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/mon-colle-knights-blu-ray-875707018920.html",
        "amzurl": "https://www.amazon.com/Knights-Japanese-Language-Collection-Blu-ray/dp/B08WJZ7W6V",
        "racsurl": "https://www.animecornerstore.com/moncokn.html",
    },
    {
        "title": "Grimm's Fairy Tale Classics: Season 1",
        "format": "sdbd",
        "released": "2021-05-25",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/grimms-fairy-tale-classics-season-1-blu-ray-875707018494.html",
        "amzurl": "https://www.amazon.com/Grimms-Fairy-Classics-Season-Blu-ray/dp/B08Z2JNQS8",
        "racsurl": "https://www.animecornerstore.com/grfatacl.html",
        "oop": "yes",
    },
    {
        "title": "Grimm's Fairy Tale Classics: Season 2",
        "format": "sdbd",
        "released": "2021-08-31",
        "msrp": "49.95",
        "amzurl": "https://www.amazon.com/Grimms-Fairy-Tale-Classics-Season/dp/B096TTS9XR",
        "racsurl": "https://www.animecornerstore.com/grfatacl.html",
        "oop": "yes",
    },
    {
        "title": "BoBoBo-Bo Bo-BoBo: The Complete Series",
        "format": "sdbd",
        "released": "2020-01-28",
        "msrp": "69.95",
        "crurl": "https://store.crunchyroll.com/products/bobobo-bo-bo-bobo-blu-ray-875707010894.html",
        "amzurl": "https://www.amazon.com/Bobobo-bo-Bo-bobo-Complete-SDBD-Blu-ray/dp/B07ZWBPMH6",
        "racsurl": "https://www.animecornerstore.com/bobobobobobobo.html",
    },
    {
        "title": "Robot Carnival (4K UHD)",
        "format": "4k",
        "released": "2021-12-28",
        "msrp": "34.95",
        "crurl": "https://store.crunchyroll.com/products/robot-carnival-4k-ultra-hd-blu-ray-875707023399.html",
        "amzurl": "https://www.amazon.com/Robot-Carnival-Blu-ray-Kohji-Moritsugu/dp/B09KN1ZYZQ",
        "racsurl": "https://www.animecornerstore.com/roca4k.html",
    },
    {
        "title": "The Legend of Calamity Jane",
        "format": "sdbd",
        "released": "2023-09-26",
        "msrp": "39.95",
        "amzurl": "https://www.amazon.com/Legend-Calamity-Jane-Animated-Blu-ray/dp/B0CBD1S7QQ",
        "racsurl": "https://www.animecornerstore.com/leofcaja.html",
    },
    {
        "title": "Kite: Integral Version",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "29.95",
        "amzurl": "https://www.amazon.com/Integral-Version-Blu-ray-Kotomi-Naruse/dp/B0DCH22CDK",
        "diaburl": "https://diabolikdvd.com/product/kite-discotek-integral-version-blu-ray/",
        "racsurl": "https://www.animecornerstore.com/kibinve.html",
    },
    {
        "title": "Ghost Stories: Complete Collection",
        "format": "bd",
        "released": "2023-02-28",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/ghost-stories-blu-ray-875707031325.html",
        "amzurl": "https://www.amazon.com/Ghost-Stories-Complete-Blu-ray-Ayres/dp/B0BQ51RJQ5",
        "racsurl": "https://www.animecornerstore.com/ghoststories.html",
    },
    {
        "title": "Reborn! Seasons 1-4",
        "format": "sdbd",
        "released": "2018-09-25",
        "msrp": "79.95",
        "crurl": "https://store.crunchyroll.com/products/reborn-volume-1-blu-ray-875707188029.html",
        "amzurl": "https://www.amazon.com/Reborn-TV-1-SDBD-Blu-ray/dp/B07FSRB4J3",
        "racsurl": "https://www.animecornerstore.com/reborn.html",
    },
    {
        "title": "Aho-Girl: The Complete Series",
        "format": "bd",
        "released": "2022-08-30",
        "msrp": "29.95",
        "crurl": "https://store.crunchyroll.com/products/aho-girl-blu-ray-875707027526.html",
    },
    {
        "title": "Berserk: The Complete 1997 TV Series",
        "format": "bd",
        "released": "2024-03-26",
        "msrp": "49.99",
        "crurl": "https://store.crunchyroll.com/products/berserk-the-complete-1997-tv-series-blu-ray-875707038591.html",
        "amzurl": "https://www.amazon.com/Berserk-Complete-1997-TV-Blu-ray/dp/B0CSF4TTNS",
        "diaburl": "https://diabolikdvd.com/product/berserk-the-complete-1997-tv-series-discotek-blu-ray/",
        "racsurl": "http://www.animecornerstore.com/berserkbr1997.html",
    },
    {
        "title": "Berserk: The Complete 1997 TV Series (Crunchyroll Exclusive Steelbook)",
        "format": "bd",
        "released": "2024-11-30",
        "msrp": "59.96",
        "crurl": "https://store.crunchyroll.com/products/berserk-the-complete-1997-tv-series-blu-ray-steelbook-crunchyroll-exclusive-875707004190.html",
    },
    {
        "title": "Dallos: Complete OVA Series",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "29.95",
        "crurl": "https://store.crunchyroll.com/products/dallos-complete-ova-series-blu-ray-875707004152.html",
        "amzurl": "https://www.amazon.com/Mamoru-Oshiis-Dallos-OVA-Blu-ray/dp/B0DCHB6T4R",
        "diaburl": "https://diabolikdvd.com/product/dallos-complete-ova-series-discotek-blu-ray/",
        "racsurl": "https://www.animecornerstore.com/dallos.html",
    },
    {
        "title": "Adventures of Sonic the Hedgehog: The Complete Series",
        "format": "sdbd",
        "released": "2022-02-22",
        "msrp": "59.95",
        "crurl": "https://store.crunchyroll.com/products/adventures-of-sonic-the-hedgehog-blu-ray-875707024099.html",
        "amzurl": "https://www.amazon.com/Adventures-Sonic-Hedgehog-Complete-SDBD/dp/B09NMSKGF9",
        "racsurl": "https://www.animecornerstore.com/adofsohe.html",
    },
    {
        "title": "Tona-Gura!",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/tonagura-complete-series-blu-ray-875707004138.html",
        "amzurl": "https://www.amazon.com/Tonagura-Complete-Blu-ray-Akemi-Kanda/dp/B0DCHF4YN6",
        "racsurl": "https://www.animecornerstore.com/tonagura.html",
    },
    {
        "title": "Reborn! Special Fan Disc",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/reborn-special-fan-disc-blu-ray-875707004183.html",
        "amzurl": "https://www.amazon.com/Reborn-Fan-Disc-Blu-ray-Neeko/dp/B0DCH7JJZF",
        "racsurl": "http://www.animecornerstore.com/respfandi.html",
    },
    {
        "title": "Lupin the Third: Italian Game",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/lupin-the-3rd-italian-game-blu-ray-875707004114.html",
        "amzurl": "https://www.amazon.com/Lupin-3rd-Italian-Game-Blu-ray/dp/B0DCHQGGDF",
        "racsurl": "https://www.animecornerstore.com/lu3rdbitga.html",
    },
    {
        "title": "Kiss x Sis: The Complete TV Series",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/kiss-x-sis-complete-tv-series-blu-ray-875707004145.html",
        "amzurl": "https://www.amazon.com/Kiss-Sis-Complete-TV-Blu-ray/dp/B0DCHR9BRZ",
        "racsurl": "https://www.animecornerstore.com/kixsisbtvse.html",
    },
    {
        "title": "Street Fighter II: The Animated Movie (4K UHD)",
        "format": "4k",
        "released": "2023-11-28",
        "msrp": "34.95",
        "crurl": "https://store.crunchyroll.com/products/street-fighter-ii-the-animated-movie-4k-ultra-hd-blu-ray-875707035620.html",
        "amzurl": "https://www.amazon.com/Street-Fighter-Animated-Movie-Blu-ray/dp/B0CGWQSMJY",
        "racsurl": "https://www.animecornerstore.com/stfiiibmob4k.html",
    },
    {
        "title": "Dororo (live-action movie)",
        "format": "bd",
        "released": "2024-11-26",
        "msrp": "24.95",
        "crurl": "https://store.crunchyroll.com/products/dororo-live-action-movie-blu-ray-875707004824.html",
        "amzurl": "https://www.amazon.com/Dororo-Live-Action-Movie-Blu-ray/dp/B0DGVZ2267",
        "diaburl": "https://diabolikdvd.com/product/dororo-live-action-movie-discotek-blu-ray/",
    },
    {
        "title": "Giant Gorg",
        "format": "bd",
        "released": "2024-11-26",
        "msrp": "49.95",
        "crurl": "https://store.crunchyroll.com/products/giant-gorg-complete-tv-series-blu-ray-875707004398.html",
        "amzurl": "https://www.amazon.com/Giant-Gorg-Complete-TV-Blu-ray/dp/B0DGVYF5WP",
        "racsurl": "https://www.animecornerstore.com/giantgorg.html",
    },
    {
        "title": "Groizer X",
        "format": "sdbd",
        "released": "2024-11-26",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/groizer-x-complete-series-blu-ray-875707004596.html",
        "amzurl": "https://www.amazon.com/Groizer-X-Complete-TV-Blu-ray/dp/B0DGW57ZLQ",
        "racsurl": "https://www.animecornerstore.com/groizerx.html",
    },
    {
        "title": "Humanoid Monster BEM",
        "format": "bd",
        "released": "2024-11-26",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/humanoid-monster-bem-original-animated-tv-series-blu-ray-875707004794.html",
        "amzurl": "https://www.amazon.com/Humanoid-Monster-Original-Animated-Blu-ray/dp/B0DGVTM7WW",
        "diaburl": "https://diabolikdvd.com/product/humanoid-monster-bem-original-animated-tv-series-discotek-blu-ray/",
        "racsurl": "https://www.animecornerstore.com/humobem.html",
    },
    {
        "title": "MXC: Most Extreme Elimination Challenge: Set 1",
        "format": "sdbd",
        "released": "2024-11-26",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/mxc-most-extreme-elimination-challenge-collection-1-blu-ray-875707004992.html",
        "amzurl": "https://www.amazon.com/MXC-Extreme-Elimination-Challenge-Collection/dp/B0DGVSCJ22",
        "diaburl": "https://diabolikdvd.com/product/mxc-most-extreme-elimination-challenge-v1-discotek-blu-ray/",
        "racsurl": "http://www.animecornerstore.com/mxmoexelch.html",
    },
    {
        "title": "Sgt. Frog: The Complete Fifth, Sixth, and Seventh Season",
        "format": "sdbd",
        "released": "2024-11-26",
        "msrp": "59.95",
        "crurl": "https://store.crunchyroll.com/products/sgt-frog-the-complete-fifth-sixth-and-seventh-season-blu-ray-875707004428.html",
        "amzurl": "https://www.amazon.com/Sgt-Frog-Seasons-5-7-Blu-ray/dp/B0DGWG4JL9",
        "racsurl": "https://www.animecornerstore.com/sgtfrog.html",
    },
    {
        "title": "Belladonna of Sadness",
        "format": "4kbd",
        "released": "2024-05-28",
        "msrp": "39.95",
        "crurl": "https://store.crunchyroll.com/products/belladonna-of-sadness-movie-4k-blu-ray-875707039420.html",
        "amzurl": "https://www.amazon.com/Belladonna-Sadness-4K-UHD-Blu-ray/dp/B0CW7GPKL6",
        "diaburl": "https://diabolikdvd.com/product/belladonna-of-sadness-discotek-4k-uhd-blu-ray/",
        "racsurl": "https://www.animecornerstore.com/beofsab4k2k.html",
    },
    {
        "title": "Captain Harlock: Space Pirate: TV Series Complete Collection",
        "format": "bd",
        "released": "2024-09-24",
        "msrp": "69.95",
        "crurl": "https://store.crunchyroll.com/products/captain-harlock-original-tv-series-blu-ray-875707004107.html",
        "amzurl": "https://www.amazon.com/Captain-Harlock-Pirate-Complete-Blu-ray/dp/B0DCHNDCR2",
        "diaburl": "https://diabolikdvd.com/product/captain-harlock-original-tv-series-discotek-blu-ray/",
        "racsurl": "https://www.animecornerstore.com/captainharlock.html",
    },
    {
        "title": "GTO: Great Teacher Onizuka The Animation: Complete Collection",
        "format": "sdbd",
        "released": "2024-09-24",
        "msrp": "59.95",
        "crurl": "https://store.crunchyroll.com/products/gto-great-teacher-onizuka-the-animation-complete-collection-blu-ray-875707004169.html",
        "amzurl": "https://www.amazon.com/Great-Teacher-Onizuka-Animation-Blu-ray/dp/B0DCHDCQDR",
        "racsurl": "https://www.animecornerstore.com/gtgrteon.html",
    },
    {
        "title": "Digimon: The Movies: Movie Collection 1 (Movies 1-3)",
        "format": "bd",
        "released": "2024-12-17",
        "msrp": "29.95",
        "crurl": "https://store.crunchyroll.com/products/digimon-the-movies-movies-1-3-blu-ray-875707005029.html",
        "amzurl": "https://www.amazon.com/Digimon-Movies-1-3-Collection-Blu-ray/dp/B0DGW7SQFC",
        "racsurl": "https://www.animecornerstore.com/dibmo.html",
    },
];
function compareRelease( a, b ) {
    if ( a.released > b.released ){
      return -1;
    }
    if ( a.released < b.released ){
      return 1;
    }
    return 0;
}
function compareTitle( a, b ) {
    if (a.title < b.title) {
        return -1;
      }
      if (a.title > b.title) {
        return 1;
      }
      return 0;
    };
catalogItems.sort( compareTitle );
catalogItems.sort( compareRelease );